version: '3'
services:
	nginx:
		build: ./requirements/nginx
		container_name: nginx
		image: nginx
		ports:
			- 80:80
			- 443:443
		networks:
			- internal
		volumes:
			- wordpress:var/www/html
		depends_on:
			- wordpress
			- mariadb
		restart: always
		environment:
			NG_WP_NAME: ${NG_WP_NAME}
			WP_PORT: ${NG_WP_PORT}
			DOMAIN_NAME: ${DOMAIN_NAME}

	wordpress:
		build: ./requirements/wordpress
		container_name: wordpress
		image: wordpress
		expose:
			- ${NG_WP_PORT}
		volumes:
			- wordpress:/var/www/html
		networks:
			- internal
		restart: always
		environment:
			DB: ${WP_DB_NAME}
			DBUSER: ${MDB_USER_NAME}
			DB_PWD: ${MDB_ROOT_PASS}
			DB_HOST: ${MDB_HOST}
			ADMIN: ${WP_DB_USR}
			ADMINPWD: ${WP_DB_PWD}
			ADMINEMAIL: ${WP_ADMIN_EMAIL}
			WP_TITLE: ${WP_TITLE}
			DOMAIN_NAME: ${DOMAIN_NAME}
			WP_USER_LOGIN: ${WP_USER_LOGIN}
			WP_USER_PWD: ${WP_USER_PWD}
			WP_USER_EMAIL: ${WP_USER_EMAIL
}
	 mariadb:
		build: ./requirements/mariadb
		container_name: mariadb
		image: mariadb
		hostname: mariadb
		expose:
			- 3306
		volumes:
			- db:var/lib/mysql
		networks:
			- internal
		restart: on-failure
		init :true
		environment:
			WP_DB_NAME: ${WP_DB_NAME}
			MDB_HOST: ${MDB_HOST}
			MDB_PORT: ${MDB_PORT}
			MDB_USER_NAME: ${MDB_USER_NAME}
			MARIADB_USER_PWD:  ${MARIADB_USER_PASS)
			MARIADB_ROOT_PWD:  ${MARIADB_ROOT_PASS}

volumes:
	db:
		name: db
		driver: local
		driver_opts:
			type: none
			device: /home/${USER}/data/
			o: bind
	wordpress:
		name: wp
		driver: local
		driver_opts:
			type: none
			device: /home/${USER}/data/
			o: bind

networks:
	internal:
