version: '3'

services:
  nginx:
    hostname: rdas-nev.42.fr
    container_name: rdas-nev_nginx
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    image: nginx
    restart: always
    volumes:
      - wp:/var/www/html
    ports:
      - '443:443'
    depends_on:
      - wordpress

  wordpress:
    container_name: rdas-nev_wordpress
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    image: wordpress
    restart: always
    volumes:
      - wp:/var/www/html
    env_file:
      - .env

  mariadb:
    container_name: rdas-nev_mariadb
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    image: mariadb
    expose:
     - 3306
    restart: always
    volumes:
      - db:/var/lib/mysql
    env_file:
      - .env
networks:
    default:
      name: rdas-nev_inception

volumes:
  wp:
    name: wp
    driver: local
    driver_opts:
      device: /home/rdas-nev/data
      o: bind
      type: none
  db:
    name: db
    driver: local
    driver_opts:
      device: /home/rdas-nev/data
      o: bind
      type: none

