version: '3'

services:
  nginx:
    hostname: rdas-nev.42.fr
    container_name: rdas-nev_nginx
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    image: nginx
    restart: always
    volumes:
      - wp:/var/www/html
    ports:
      - '443:443'
    depends_on:
      - wordpress

  wordpress:
    container_name: rdas-nev_wordpress
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    image: wordpress
    restart: always
    volumes:
      - wp:/var/www/html
    env_file:
      - .env

  mariadb:
    container_name: rdas-nev_mariadb
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    image: mariadb
    expose:
     - 3306
    restart: always
    volumes:
      - db:/var/lib/mysql
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DB_HOST: rdas-nev_mariadb
      ADMIN_USER: ${ADMIN_LOGIN}
      ADMIN_PASSWORD: ${ADMIN_PWD}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      WP_TITLE: ${WP_TITLE}
      DOMAIN_NAME: ${DOMAIN_NAME}
      WP_USER_LOGIN: ${USER_LOGIN}
      WP_USER_EMAIL: ${USER_EMAIL}
      WP_USER_PASS: ${USER_PASSWORD}
networks:
    default:
      name: rdas-nev_inception

volumes:
  wp:
    name: wp
    driver: local
    driver_opts:
      device: /root/wordpress
      o: bind
      type: none
  db:
    name: db
    driver: local
    driver_opts:
      device: /root/database
      o: bind
      type: none

